### ISSUE TITLE
Suddenly receiving appcenter.derived_client.AppCenterHTTPException

### ISSUE THREAD

**Issue by awBSH** [microsoft/appcenter-rest-python#13]
Since approx. 10:00 AM CET we are receiving *appcenter.derived_client.AppCenterHTTPException* from appcenter/crashes.py
`
23-Feb-2022 10:19:34 | Traceback (most recent call last):
-- | --
23-Feb-2022 10:19:34 | File "analyse_crashes.py", line 458, in <module>
23-Feb-2022 10:19:34 | main()
23-Feb-2022 10:19:34 | File "analyse_crashes.py", line 350, in main
23-Feb-2022 10:19:34 | android_reu_groups = android_reu_crashes_handler.groups()
23-Feb-2022 10:19:34 | File "analyse_crashes.py", line 79, in groups
23-Feb-2022 10:19:34 | groups = list(self.client.get_error_groups(owner_name=self.owner_name,
23-Feb-2022 10:19:34 | File "/Users/bamboo/Library/Python/3.8/lib/python/site-packages/appcenter/crashes.py", line 208, in get_error_groups
23-Feb-2022 10:19:34 | response = self.get(request_url)
23-Feb-2022 10:19:34 | File  "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tenacity/__init__.py",  line 333, in wrapped_f
23-Feb-2022 10:19:34 | return self(f, *args, **kw)
23-Feb-2022 10:19:34 | File  "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tenacity/__init__.py",  line 423, in __call__
23-Feb-2022 10:19:34 | do = self.iter(retry_state=retry_state)
23-Feb-2022 10:19:34 | File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tenacity/__init__.py", line 360, in iter
23-Feb-2022 10:19:34 | return fut.result()
23-Feb-2022 10:19:34 | File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
23-Feb-2022 10:19:34 | return self.__get_result()
23-Feb-2022 10:19:34 | File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
23-Feb-2022 10:19:34 | raise self._exception
23-Feb-2022 10:19:34 | File  "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tenacity/__init__.py",  line 426, in __call__
23-Feb-2022 10:19:34 | result = fn(*args, **kwargs)
23-Feb-2022 10:19:34 | File "/Users/bamboo/Library/Python/3.8/lib/python/site-packages/appcenter/derived_client.py", line 185, in get
23-Feb-2022 10:19:34 | raise create_exception(response)
23-Feb-2022 10:19:34 | appcenter.derived_client.AppCenterHTTPException:  <method=GET,  url=https://api.appcenter.ms/v0.1/apps/Home-Connect/Home-Connect-App-1/errors/errorGroups?start=2021-11-25T11%3A19%3A03&$top=30&$token=e7cbb259-aeed-407b-8d63-1eb61d241b84,  status_code=502, text={"message":"internal error","err_message":"error:  activity_name: graph router, exception: ESOCKETTIMEDOUT,  current_request_url:  /v0.1/apps/Home-Connect/Home-Connect-App-1/errors/errorGroups?start=2021-11-25T11%3A19%3A03&$top=30,  api_path: v0.1/apps/{owner_name}/{app_name}/errors/errorGroups, beacon:  errors, code: ESOCKETTIMEDOUT. Correlation ID:  14863e1b-34c7-4d46-b3fa-7e6897c60faf"}>

`

**Comment by dalemyers** [comment]
A 502 error indicates that this is an App Center issue rather than an SDK issue. If this persists, you'll need to contact them directly. This SDK is actually owned by the Outlook Mobile team. Please re-open if this doesn't go away though.
