### ISSUE TITLE
BuildInfo not deserialized correctly

### ISSUE THREAD

**Issue by bastianh** [microsoft/appcenter-rest-python#16]
Hi, 

I noticed when you call `client.versions.all()` in the result the `BuildInfo` object remains empty for all versions, because it is trying to deserialize the keys from the response `branchName`, `commitHash` and `commitMessage` into the object with the keys `branch_name`, `commit_hash` and `commit_message`.

Bastian

**Comment by dalemyers** [comment]
This should now be fixed and published in 3.2.0. Thanks for the report!
