### ISSUE TITLE
Client stopped working with 403.

### ISSUE THREAD

**Issue by echorebel** [microsoft/appcenter-rest-python#3]
We are using appcenter for nightly and weekly builds. Client suddenly stopped working tonight with a 403 invalid token.
We didn't touched our script nor our access tokens.
Already checked status.appcenter.ms but distribute status is green there. Was there a change on the API that not reflected in the client?

**Comment by dalemyers** [comment]
There's been no change that I'm aware of. Tokens do expire though, so it would be worth re-generating to confirm if that was the reason or not.

**Comment by dalemyers** [comment]
Ah, sorry, just catching up on everything today and I've just learned that there was an AAD outage last night. That's likely to be the case. It seems that it has been mitigated, but there may be some lingering issues. If you can check again to see if it has been resolved already, that would be great. Otherwise you may need to wait a few hours.

**Comment by echorebel** [comment]
Thx for quick info, I saw second message too late just replaced the key but it's also not working. Also there is not info on the appcenter page that they would expire at all. I saw the AAD outage but what does it mean actually?
Waiting now few hours i guess. I keep u posted here and close the issue when it's working again.

**Comment by dalemyers** [comment]
AAD is the auth system that powers Microsoft services. Last night it had an issue which caused it to be inaccessible. This meant that every request which required authentication of some kind (such as API requests to app center), stopped working. A fix was made, but it takes time to roll out, clear out old cached data, etc. 

I'd expect things to be working now for you though. Could you share the code you are using to make the call, as well as the exact response you are getting from App Center?

**Comment by echorebel** [comment]
Doesn't work yet, we still get:
```
appcenter.derived_client.AppCenterDecodedHTTPException: method=GET, url=https://api.appcenter.ms/v0.1/apps/Administrator-Organization/mytaxi-Passenger-Alpha-1/uploads/releases/dac8c292-e0cd-4685-a233-b31fdc286491, status_code=403, error=<code=ValidationFailure, message=invalid token>
```
our code is simple in short:
```
client = appcenter.AppCenterClient(access_token=access_token)
client.versions.upload_and_release(
    owner_name=owner_name,
    app_name=app_name,
    version=version,
    build_number=p["buildNumber"],
    binary_path=file,
    group_id=public_group,
    release_notes=release_notes,
    branch_name=branch
)
```

**Comment by dalemyers** [comment]
That's quite interesting. It seems that some calls are working but others are not. `upload_and_release` does a few things. The call that is failing is a `GET` rather than a `POST`/`PUT` which is unusual. The only place that really makes sense is when it is waiting for the upload to complete. 

Let's see if that's the case. Try running this code:

```python
create_release_upload_response = client.versions.get_upload_url(
    owner_name=owner_name, app_name=app_name
)

success = client.versions.upload_binary(
    create_release_upload_response=create_release_upload_response, binary_path=binary_path
)

if not success:
    raise Exception("Failed to upload binary")

client.versions.commit_upload(
    owner_name=owner_name,
    app_name=app_name,
    upload_id=create_release_upload_response.identifier,
)

upload_end_response = client.versions._wait_for_upload(
    owner_name=owner_name,
    app_name=app_name,
    upload_id=create_release_upload_response.identifier,
)

build_info = BuildInfo(
    branch_name=branch_name, commit_hash=commit_hash, commit_message=commit_message
)
update_request = ReleaseUpdateRequest(release_notes=release_notes, build=build_info)

client.versions.update_release(
    owner_name=owner_name,
    app_name=app_name,
    release_id=upload_end_response.release_distinct_id,
    release_update_request=update_request,
)
```


Then let's see where it fails.

**Comment by echorebel** [comment]
First try upload seem to work, then i was missing BuildInfo import/definition. Second try failed on upload straight:
```
Failed to post in get_upload_url: method=POST, url=https://api.appcenter.ms/v0.1/apps/super-secrete-org/alpha-1/uploads/releases, status_code=403, error=<code=ValidationFailure, message=invalid token> 
```
where do u get `BuildInfo` and `ReleaseUpdateRequest` from?

**Comment by dalemyers** [comment]
You can import them by `from appcenter.models import BuildInfo, ReleaseUpdateRequest`, however, it seems that it is failing on getting the upload URL which is the very first step. 

Based on this info, it seems like it is an app center issue, not a library issue, but let's confirm that to be on the safe side. Try this:

```python
import requests

owner_name = "[put owner name here]"
app_name = "[put app name here]"
token = "[put API token here]"
request_url = f"https://api.appcenter.ms/v0.1/apps/{owner_name}/{app_name}/uploads/releases"

response = requests.post(
    request_url, 
    headers={"Content-Type": "application/json", "X-API-Token": token},
    json={}
)

print(response.text)
```

If that fails, it's an app center issue and you'll need to contact their support unfortunately.

**Comment by echorebel** [comment]
Ok thx for support, aprreciated. Definetly no problem of the lib.
If fails and only works occassionaly.
