### ISSUE TITLE
Multi-threaded requests

### ISSUE THREAD

**Issue by imWildCat** [microsoft/appcenter-rest-python#4]
While [getting crash groups](https://github.com/microsoft/appcenter-rest-python/blob/master/appcenter/crashes.py#L208) and crashes, the operation will take a long time if the number of crash groups is very large.

Is that possible to get the total number of pages and download the crash group data using multiple threads?

**Comment by dalemyers** [comment]
There may be a way, but I'm not familiar with it. The way this works is that we issue a request and it gives us a page of results along with a link to the next page. We'd basically need to get the first page, and they'd need to give us a link to _all_ of the other pages. Might be worth contacting App Center support to find out?

**Comment by imWildCat** [comment]
No problem. Thanks Dale!

Since this is related to App Center itself, we can close this issue first.
